// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using entities;

namespace entities.Migrations
{
    [DbContext(typeof(EFApplicationContext))]
    [Migration("20200214211251_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("entities.entity.Xpto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<double>("TotalPlanned1")
                        .HasColumnName("total_planned1");

                    b.Property<double>("TotalPlanned10")
                        .HasColumnName("total_planned10");

                    b.Property<double>("TotalPlanned11")
                        .HasColumnName("total_planned11");

                    b.Property<double>("TotalPlanned2")
                        .HasColumnName("total_planned2");

                    b.Property<double>("TotalPlanned3")
                        .HasColumnName("total_planned3");

                    b.Property<double>("TotalPlanned4")
                        .HasColumnName("total_planned4");

                    b.Property<double>("TotalPlanned5")
                        .HasColumnName("total_planned5");

                    b.Property<double>("TotalPlanned6")
                        .HasColumnName("total_planned6");

                    b.Property<double>("TotalPlanned7")
                        .HasColumnName("total_planned7");

                    b.Property<double>("TotalPlanned8")
                        .HasColumnName("total_planned8");

                    b.Property<double>("TotalPlanned9")
                        .HasColumnName("total_planned9");

                    b.Property<double>("TotalProduced1")
                        .HasColumnName("total_produced1");

                    b.Property<double>("TotalProduced10")
                        .HasColumnName("total_produced10");

                    b.Property<double>("TotalProduced11")
                        .HasColumnName("total_produced11");

                    b.Property<double>("TotalProduced2")
                        .HasColumnName("total_produced2");

                    b.Property<double>("TotalProduced3")
                        .HasColumnName("total_produced3");

                    b.Property<double>("TotalProduced4")
                        .HasColumnName("total_produced4");

                    b.Property<double>("TotalProduced5")
                        .HasColumnName("total_produced5");

                    b.Property<double>("TotalProduced6")
                        .HasColumnName("total_produced6");

                    b.Property<double>("TotalProduced7")
                        .HasColumnName("total_produced7");

                    b.Property<double>("TotalProduced8")
                        .HasColumnName("total_produced8");

                    b.Property<double>("TotalProduced9")
                        .HasColumnName("total_produced9");

                    b.HasKey("Id")
                        .HasName("pk_xpto");

                    b.ToTable("xpto","entity");
                });

            modelBuilder.Entity("entities.xpto.Planned", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<double>("Planned1")
                        .HasColumnName("planned1");

                    b.Property<double>("Planned10")
                        .HasColumnName("planned10");

                    b.Property<double>("Planned11")
                        .HasColumnName("planned11");

                    b.Property<double>("Planned2")
                        .HasColumnName("planned2");

                    b.Property<double>("Planned3")
                        .HasColumnName("planned3");

                    b.Property<double>("Planned4")
                        .HasColumnName("planned4");

                    b.Property<double>("Planned5")
                        .HasColumnName("planned5");

                    b.Property<double>("Planned6")
                        .HasColumnName("planned6");

                    b.Property<double>("Planned7")
                        .HasColumnName("planned7");

                    b.Property<double>("Planned8")
                        .HasColumnName("planned8");

                    b.Property<double>("Planned9")
                        .HasColumnName("planned9");

                    b.HasKey("Id")
                        .HasName("pk_vol_planned");

                    b.ToTable("vol_planned","xpto");
                });

            modelBuilder.Entity("entities.xpto.Produced", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<double>("Produced1")
                        .HasColumnName("produced1");

                    b.Property<double>("Produced10")
                        .HasColumnName("produced10");

                    b.Property<double>("Produced11")
                        .HasColumnName("produced11");

                    b.Property<double>("Produced2")
                        .HasColumnName("produced2");

                    b.Property<double>("Produced3")
                        .HasColumnName("produced3");

                    b.Property<double>("Produced4")
                        .HasColumnName("produced4");

                    b.Property<double>("Produced5")
                        .HasColumnName("produced5");

                    b.Property<double>("Produced6")
                        .HasColumnName("produced6");

                    b.Property<double>("Produced7")
                        .HasColumnName("produced7");

                    b.Property<double>("Produced8")
                        .HasColumnName("produced8");

                    b.Property<double>("Produced9")
                        .HasColumnName("produced9");

                    b.Property<double>("Total")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_vol_produced");

                    b.ToTable("vol_produced","xpto");
                });

            modelBuilder.Entity("security.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasColumnName("codigo");

                    b.Property<bool>("Desativado")
                        .HasColumnName("desativado");

                    b.Property<string>("Nome")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.ToTable("modulo","security");
                });

            modelBuilder.Entity("security.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("Desativado")
                        .HasColumnName("desativado");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnName("normalized_name")
                        .HasMaxLength(256);

                    b.HasKey("Id")
                        .HasName("pk_aspnetroles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("role_name_index");

                    b.ToTable("aspnetroles","security");
                });

            modelBuilder.Entity("security.PerfilClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroleclaims");

                    b.HasIndex("RoleId")
                        .HasName("ix_aspnetroleclaims_role_id");

                    b.ToTable("aspnetroleclaims","security");
                });

            modelBuilder.Entity("security.PerfilModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("Desativado")
                        .HasColumnName("desativado");

                    b.Property<Guid>("ModuloId")
                        .HasColumnName("modulo_id");

                    b.Property<Guid>("PerfilId")
                        .HasColumnName("perfil_id");

                    b.HasKey("Id")
                        .HasName("pk_perfil_modulo");

                    b.HasIndex("ModuloId")
                        .HasName("ix_perfil_modulo_modulo_id");

                    b.HasIndex("PerfilId")
                        .HasName("ix_perfil_modulo_perfil_id");

                    b.ToTable("perfil_modulo","security");
                });

            modelBuilder.Entity("security.PerfilModuloPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("Desativado")
                        .HasColumnName("desativado");

                    b.Property<Guid>("PerfilModuloId")
                        .HasColumnName("perfil_modulo_id");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnName("permissao_id");

                    b.HasKey("Id")
                        .HasName("pk_modulo_permissao");

                    b.HasIndex("PerfilModuloId")
                        .HasName("ix_modulo_permissao_perfil_modulo_id");

                    b.HasIndex("PermissaoId")
                        .HasName("ix_modulo_permissao_permissao_id");

                    b.ToTable("modulo_permissao","security");
                });

            modelBuilder.Entity("security.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasColumnName("codigo");

                    b.Property<bool>("Desativado")
                        .HasColumnName("desativado");

                    b.Property<string>("Nome")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_permissao");

                    b.ToTable("permissao","security");
                });

            modelBuilder.Entity("security.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CpjCnpj")
                        .HasColumnName("cpj_cnpj")
                        .HasMaxLength(14);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("Desativado")
                        .HasColumnName("desativado");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(40);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnName("normalized_email")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnName("normalized_user_name")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasMaxLength(256);

                    b.HasKey("Id")
                        .HasName("pk_aspnetusers");

                    b.HasIndex("NormalizedEmail")
                        .HasName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("user_name_index");

                    b.ToTable("aspnetusers","security");
                });

            modelBuilder.Entity("security.UsuarioClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_aspnetuserclaims");

                    b.HasIndex("UserId")
                        .HasName("ix_aspnetuserclaims_user_id");

                    b.ToTable("aspnetuserclaims","security");
                });

            modelBuilder.Entity("security.UsuarioLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_aspnetuserlogins");

                    b.HasIndex("UserId")
                        .HasName("ix_aspnetuserlogins_user_id");

                    b.ToTable("aspnetuserlogins","security");
                });

            modelBuilder.Entity("security.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_aspnetuserroles");

                    b.HasIndex("RoleId")
                        .HasName("ix_aspnetuserroles_role_id");

                    b.ToTable("aspnetuserroles","security");
                });

            modelBuilder.Entity("security.UsuarioToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_aspnetusertokens");

                    b.ToTable("aspnetusertokens","security");
                });

            modelBuilder.Entity("security.PerfilClaim", b =>
                {
                    b.HasOne("security.Perfil")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_aspnetroleclaims_aspnetroles_role_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("security.PerfilModulo", b =>
                {
                    b.HasOne("security.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .HasConstraintName("fk_perfil_modulo_modulo_modulo_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("security.Perfil", "Perfil")
                        .WithMany("Modulos")
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_perfil_modulo_aspnetroles_perfil_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("security.PerfilModuloPermissao", b =>
                {
                    b.HasOne("security.PerfilModulo", "PerfilModulo")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilModuloId")
                        .HasConstraintName("fk_modulo_permissao_perfil_modulo_perfil_modulo_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("security.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .HasConstraintName("fk_modulo_permissao_permissao_permissao_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("security.UsuarioClaim", b =>
                {
                    b.HasOne("security.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_aspnetuserclaims_aspnetusers_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("security.UsuarioLogin", b =>
                {
                    b.HasOne("security.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_aspnetuserlogins_aspnetusers_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("security.UsuarioPerfil", b =>
                {
                    b.HasOne("security.Perfil", "Role")
                        .WithMany("Papeis")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_aspnetuserroles_aspnetroles_role_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("security.Usuario", "User")
                        .WithMany("Papeis")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_aspnetuserroles_aspnetusers_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("security.UsuarioToken", b =>
                {
                    b.HasOne("security.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_aspnetusertokens_aspnetusers_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
